def foo():
     raise TypeError("Test-Exception")
